name: Publish to npm

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read Node version from .node-version
        run: echo "node_version=$(cat .node-version)" >> $GITHUB_OUTPUT
        id: node-version

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.node-version.outputs.node_version }}
          registry-url: 'https://registry.npmjs.org'
          scope: '@zenkigen-inc'
          always-auth: true

      - name: Install dependencies
        run: yarn install

      - name: Build npm package
        run: yarn build-lib:all

      - name: Publish to npm
        run: yarn publish:all
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_OPTIONS: --max_old_space_size=8192
